#include "FractalNoise.h"
#include "Tones.Default.Settings.h"

using namespace ToneLibrary;

FractalNoise::FractalNoise()
{
    // Initialize the noise array
    // iterate over the noise array, dividing it into smaller and smaller squares with each iteration
    // Add a random offset to the midpoint value to create morex variation in the noise pattern
    // Repeat, until the desired level of detail is reached 
}

void FractalNoise::ApplyFractalNoiseFilter(FILEINFO_Obj& FileInfoObj)
{
}

/**
* Fractal Noise is a type of noise that is generated by adding 
* together multiple octaves of noise, each with a different 
* frequency and amplitude. It is used to create realistic
* patterns and textures, having a more natural organic appearance
* than regular noise.
* @param [ FileInfoObj ] --- The file parameters struct
* used to retain details for the file.
* @return [ void ] --- No return value.
*/
void FractalNoise::GenerateFractalNoise(FILEINFO_Obj& FileInfoObj)
{
    ApplyFractalNoiseFilter(FileInfoObj);
}
