IPASpellToSpeech = {
    "Consonants":
    {
        "b": "b", # as in "bat"
        "c": "k", # as in "cat"
        "ch": "ch", # as in "church, witch"
        "ck": "k", # as in "cat"
        "d": "d", # as in "dog"
        "dge": "j", # as in "jump, budget"
        "f": "f", # as in "fish"
        "g": "g", # as in "go"
        "gg": "g", # as in "go"
        "h": "h", # as in "hat"
        "j": "j", # as in "jump, budget"
        "k": "k", # as in "cat"
        "l": "l", # as in "lip"
        "ll": "l", # as in "lip"
        "m": "m", # as in "mat"
        "n": "n", # as in "nap"
        "ng": "ng", # as in "sing"
        "p": "p", # as in "pat"
        "pp": "p", # as in "pat"
        "q": "k", # as in "cat"
        "que": "k", # as in "cat"
        "que2": "k_y_oo", # as in "cat"
        "r": "r", # as in "rip"
        "s": "s", # as in "sip"
        "s2": "z", # as in "fertilise"
        "ss": "s", # as in "sip"
        "sh": "sh", # as in "sheep"
        "t": "t", # as in "tap"
        "tt": "t", # as in "tap"
        "th": "th", # as in "think, math, nothing"
        "th2": "th2", # as in "this, breathe"
        "v": "v", # as in "vat"
        "w": "w", # as in "wet"
        "wh": "hw", # as in "where, somewhat"
        "y": "y", # as in "yacht, yes, onion"
        "z": "z", # as in "zoo, zip, easy"
        "z2": "zh" # as in "measure, television, beige"
    },

    "Vowels":
    {
        "a": "a", # as in "apple, hat, bat"
        "a2": "ey", # as in "aid, bait, day"
        "a3": "ah", # as in "arm, father, aha"
        "a4": "air", # as in "air, careful, wear"
        "a5": "aw", # as in "bought"
        "e": "e", # as in "bet, ever, head"
        "e2": "ee", # as in "beet, eat, seed, need"
        "e3": "eer", # as in "teacher, murderer"
        "ea": "ee" ,# as in "beet, eat, seed, need"
        "ee": "ee", # as in "beet, eat, seed, need"
        "i": "i", # as in "it, finishes"
        "i2": "ahy", # as in "I, ice, deny"
        "ie": "ahy", # as in "I, ice, deny"
        "o": "o", # as in "odd, waffle"
        "o2": "oh", # as in "owe, road"
        "o3": "oo", # as in "rude, soup"
        "o4": "oo2", # as in "good, book"
        "o5": "ou", # as in "out, how, loud"
        "o6": "uh", # as in "up, mother"
        "oo": "oo2", # as in "rude, soup"
        "our": "oh_r", # as in "colour, road"
        "ou": "ou", # as in "out, how, loud"
        "ow": "ou", # as in "out, how, loud"
        "u": "uh", # as in "up, mother"
        "ugh": "uh", # as in "up, mother"
        "u2": "uh2", # as in "about, problem, circus"
        "u3": "ur", # as in "early, stirring"
        "y": "ee" # as in "beet, eat, seed, need"
    }
}

# Ex. "m_a_s_a_ch_oo_s_e_t_s"